Update dev deps: pyqt5 -> pyqt6
Which will hopefully avoid CI errors like:

    error: Distribution `pyqt5-qt5==5.15.17 @
    registry+https://pypi.org/simple` can't be installed because it
    doesn't have a source distribution or wheel for the current platform

    hint: You're on Windows (`win_amd64`), but `pyqt5-qt5` (v5.15.17)
    only has wheels for the following platforms: `manylinux2014_x86_64`,
    `macosx_10_13_x86_64`, `macosx_11_0_arm64`; consider adding your
    platform to `tool.uv.required-environments` to ensure uv resolves to
    a version with compatible wheels